{"name": "Авторизация под пользователем, который есть в системе", "status": "passed", "description": "При авторизация под пользователем, который есть в системе, происходит успешная авторизация", "start": 1730461579866, "stop": 1730461580410, "uuid": "6ce779f0-61ce-4576-aa3a-0c80bc9c4b6c", "historyId": "c1ee95458348aabac0acb25665322199", "testCaseId": "c1ee95458348aabac0acb25665322199", "fullName": "tests.test_login_user.Testlogin#test_login_user", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "DESKTOP-B7974RI"}, {"name": "thread", "value": "17188-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}